apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: order-service:1.0
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              value: 172.21.112.1
            - name: KAFKA_HOST
              value: 172.21.112.1
          imagePullPolicy: Always
